apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nujex76z3-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:bbe4bb669ad4c6d1bbe371aa676c7286dc6d61f1@sha256:8a71b5fcc7f8f7d0a723f4b1aeb50de79dd734289eecd1b8090dc2c0198dac5a
          name: container-image
